trigger:
  branches:
    include:
      - none
  paths:
    exclude:
      - Invoicing-Gateway-API-develop.yml
      - Invoicing-Gateway-Lookup-develop.yml
      - Build-Validation-develop.yml
      - Dockerfile.lookup
      - Dockerfile.webapi
      - docker-develop-webapi.yml
      - docker-deveop-lookup.yml
      - host_mappings.csv
pool:

          name: 'DockerAgentPool'


steps:

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/InvoicingGateway/WebAPI'
    fileType: 'json'
    targetFiles: 'appsettings.json'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Replacing log file path in log4net.config..."
            sed -i 's|<file value=".*" />|<file value="$(logfilepath)" />|' $(System.DefaultWorkingDirectory)/InvoicingGateway/WebAPI/log4net.config
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Replacing JSON Schema backward slash to forward slash in GeneratorJsonSchemaFile.cs..."
            sed -i '/GeneralJSONSchemasPath/s|\\|/|g' $(System.DefaultWorkingDirectory)/InvoicingGateway/Domain/Utils/Constants.cs
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Replacing JsonShcema paths in constants.cs..."
            sed 's@\\@/@g' $(System.DefaultWorkingDirectory)/InvoicingGateway/Domain/Utils/Constants.cs

- task: Docker@2
  displayName: Build Docker Image and Push it to Harbor
  inputs:
    containerRegistry: 'harbor_registry_service_for_GW_Apps'
    repository: 'gw-apps-dev/invoicinggw.webapi'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile.webapi'
    tags: 'develop'

